sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: king253000

  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tBSUzoP9sYuzLFpZqd3
    access-key-secret: PgGvGoEi6gkhIcPW1mcQlPkz3Yu07q
    bucket-name: kuuuure-web

